### ISSUE TITLE
CountryRegionData not exported

### ISSUE THREAD

**Issue by Bersaelor** [country-regions/react-country-region-selector#100]
Hey there,

I installed version `3.0.0` of the repo, unfortuntaley it seems the documentation is out of date, as it seems that `CountryRegionData` is no longer exported separately?

i.e.

<img width="1153" alt="Screen Shot 2020-09-26 at 13 53 49 " src="https://user-images.githubusercontent.com/4517582/94340151-b95f5f00-ffff-11ea-8e72-6de893dbc61f.png">

**Comment by benkeen** [comment]
Hmm! I'll take a look today, thanks.

**Comment by benkeen** [comment]
You're using Typescript? Looks like CountryRegionData is being exported properly but the typings file is incorrect. Looks like your IDE is picking up on that. For now, just suppress the ts error - I'll patch this in 3.0.1. Thanks!

**Comment by benkeen** [comment]
3.0.1 is now released. If you still have any trouble, let me know.

**Comment by igeligel** [comment]
I still have this error. Will look into how to fix it the following days

**Comment by iamclaytonray** [comment]
This is fixed in 3.0.2 (released today)
