### ISSUE TITLE
Documentation Typo

### ISSUE THREAD

**Issue by alphabet-codes** [country-regions/react-country-region-selector#101]
I came across a typo in the documentation while going through it
![region](https://user-images.githubusercontent.com/40604284/95176075-43ec4f00-07b4-11eb-87bc-437a92e05e9a.png)

**Comment by alphabet-codes** [comment]
I'm interested in submitting a pull request that fixes this issue.

**Comment by benkeen** [comment]
Possibly my English is a bit funny, but that reads just fine to me. That said, if you fancy making my English _not_ suck, PRs welcome!

**Comment by alphabet-codes** [comment]
Thanks

**Comment by alphabet-codes** [comment]
Have successfully submitted a pull request. I'd be honored if it gets merged. @benkeen

**Comment by benkeen** [comment]
Merged, thanks @alphabet-codes :)
