### ISSUE TITLE
Kosovo is not added in country List

### ISSUE THREAD

**Issue by Parina512** [country-regions/react-country-region-selector#105]
here I'm using react-country-region-selector's version 3.0.1 and not getting kosovo in country list and by using customOptions as attribute in <RegionDropdown> also not getting country name in dropdown

As I can see in package.json it is using  "country-region-data": "^1.6.0" and in  country-region-data' version 1.6.0 source code contain kosovo in data.json

**Comment by Parina512** [comment]
Hello any updates on this? Still I'm not able to see KOSOVO in CountryDropdown of new version 3.0.2

**Comment by benkeen** [comment]
Resolved.
https://country-regions.github.io/react-country-region-selector/
