### ISSUE TITLE
required attribute wrongly disallowed by typings

### ISSUE THREAD

**Issue by ExplodingCabbage** [country-regions/react-country-region-selector#108]
Per https://github.com/country-regions/react-country-region-selector/issues/72, passing a `required` attribute to one of the dropdowns defined in this library is meant to be kosher, but if you try to do so in TypeScript, you'll get a type error.

I think the solution to this may simply be to replace `Element` with `HTMLSelectElement` in index.d.ts?

**Comment by benkeen** [comment]
Thanks! This is now properly supported in `4.0.0`.
