### ISSUE TITLE
Can we get the data values updated to 1.7.0?

### ISSUE THREAD

**Issue by cweston171** [country-regions/react-country-region-selector#109]
Just a request to update the version for https://github.com/country-regions/country-region-data feeding selection options to 1.7.0 within this plugin.

Specifically the country-region-data that it relies on is old/out of date. The latest in github looks valid at 1.7.0 and doesn't have GLA which is listed as "Glaslow, City of", which isn't valid.

**Comment by benkeen** [comment]
Sorry about that. We're up to 1.11.0 now.
