### ISSUE TITLE
dropdown props missing "style" property in typescript type definition

### ISSUE THREAD

**Issue by maxeth** [country-regions/react-country-region-selector#117]
The docs show an example of manually styling the dropdown using the ```style``` attribute, yet the attribute is not recognized by typescript on neither the CountryDropdown nor the RegionDropdown. I haven't looked into it thoroughly, but I believe it would be good to add  

```
 style?: React.CSSProperties;
```
to the (Country- &)RegionDropdownProps interface in the ```index.d.ts``` file.

**Comment by sawfiz** [comment]
I encountered the same issue.

Did you find a workaround?

**Comment by benkeen** [comment]
Thanks folks. `className` and `style` are now both supported in `4.0.0`. Note that `classes` was deprecated in favour of `className`. Closing.
