### ISSUE TITLE
Add support for dark mode for the country region selector

### ISSUE THREAD

**Issue by smitit173** [country-regions/react-country-region-selector#119]
Need dark mode support for the country and region dropdowns

<img width="546" alt="Screenshot 2021-09-21 at 3 05 02 PM" src="https://user-images.githubusercontent.com/26775288/134147890-0fb91b14-b2b8-4a68-897c-d2583f723818.png">

As seen in the image, the input field needs to blend with the background and also the selected text is not visible in the dark mode

**Comment by benkeen** [comment]
Hi @smitit173, for this you'll need to style it on your end. The fields are just plain HTML <select> fields, so can be styled accordingly. You can pass a class to the component if that helps - but more likely you'll want a broader styling for all dropdown fields to make them styled as such. 

All the best!

**Comment by smitit173** [comment]
Thanks for the quick response @benkeen :)
