### ISSUE TITLE
Option not selected when value is present.

### ISSUE THREAD

**Issue by zthornto** [country-regions/react-country-region-selector#12]
I have this package (which has been great outside of this one quirk - thank you) implemented, and it's not displaying a selected option when a value is passed into the component.

```
<CountryDropdown
    valueType="short"
    whitelist={Constants.countriesList}
    value={this.state.country}
    onChange={(val) => this.selectCountry(val)}
/>
```

In the above example, I have confirmed that this.state.country is equal to "US", and the select has an option with a value of "US" after setting valueType="short".

The RegionDropdown correctly shows a list of US states, but has the same issue as the CountryDropdown in that it displays the default 'Select Region' value as opposed to showing a selected state option. 

Note (for clarity) that everything works fine when selecting new/different options - I'm only talking about displaying the proper selected option when the page loads, which is a common use-case when editing data.

**Comment by zthornto** [comment]
As a follow up - I should have mentioned that i'm not sure if this is expected or not. If I call selectCountry and selectRegion when the data mounts, all is well - but I do know that React will display selected options out of the box, so it'd be nice if that functionality worked here as well.

**Comment by tchaffee** [comment]
Is anyone already working to fix this? I need it and it looks fairly easy to fix, but I don't want to duplicate effort if someone is already on it.

**Comment by bebbi** [comment]
The PR is to make the component controlled, that fixes the issues of select not updating when value is changed.
Can you check if this fixes it for you?
