### ISSUE TITLE
4.0.0 - changes a' comin'

### ISSUE THREAD

**Issue by benkeen** [country-regions/react-country-region-selector#123]
Hey all. I need to learn Nx, and this is a perfect little package to experiment with.

So in the next few weeks I'm going to take a little time to do a bunch of spring (fine, winter) cleaning:
- convert the repo to Nx
- update the country-region-data package to have a new export of proper es6 code for the country data. This's greatly simplify keeping your bundle sizes small if you only want a subset of the data
- review all open issues and make whatever changes I can. 
- update the React code. It's gettin' a bit old!

**Comment by iamclaytonray** [comment]
I have some suggestions & could also collab if you want/need.

1. [Preconstruct](https://preconstruct.tools/) is really neat
2. Rewriting in TypeScript would be neat
3. Rewrite defaultProps to default values (when destructuring props). React Core has decided to deprecate defaultProps for functional components (at least). (ex: `const Ex = ({ items = [], ... }) => { ... }`

**Comment by benkeen** [comment]
Hey! Yeah, help always appreciated - let me just figure out how to tackle it and I'll post here with the plan. 

1. Huh, don't know that one. But I think for now I just want to use Nx; it's something I need to try for work, so that'll be enough for now. 
2. Agreed! Let's make it TS. 
3. Agreed. Bit cleaner.
4. What sort of change are you thinking here? Change the API of the onChange callback itself? It's a bit non-standard, but in the vast majority of cases I find people just want the selected value, so making that the first prop is pretty convenient - saves people having to fish around with `event.target.value` to extract the value. And there's always the second event prop if they need more info. I also don't _awfully_ want to break the API for people upgrading - not for something fundamental like that. It would necessitate everyone having to update their code which I'm hoping to avoid here.

**Comment by benkeen** [comment]
Heya, so quick update on this. I'm working on:
- getting Nx set up so the package builds. For now I'm just going to rename the files to .ts and suppress any warnings. The code updates can come next. 
- I'm going to drop the custom demo page and just use Storybook instead for local development & for the github pages. 

Once this much is working I'll update the doc for instructions on how to work locally and post back here.

**Comment by benkeen** [comment]
Another update. Nx is going well, but I've decided to make a number of breaking changes after all. Above all I want to make it easier for people to generate smaller bundle sizes - importing all of country-region-data massively increased the amount of code needed to be downloaded. So I've entirely separated the components from the data source and added a provider component to let you supply the data itself. 

Current plan: 

```
import { Provider, CountrySelector, RegionSelector } from "react-country-region-selector";
import { allCountries, CA, US, UK, NZ } from "country-region-data";

// All countries
<Provider countries={allCountries}>
    <CountrySelector />
    <RegionSelector />
</Provider>

// specific countries (or provider your own info)
<Provider countries={[CA, US, UK, NZ]}>
    <CountrySelector />
    <RegionSelector />
</Provider>
```

**Comment by iamclaytonray** [comment]
This is looking good. Sorry for the delay, had a release this week at work 😅 

re: onChange handler

It may be slightly easier to just access the direct value as the first arg but it makes integration with form libraries (react-hook-form, formik) very convoluted. These form libraries have really grown in popularity because most people realize it's difficult managing validation state, regular form state, etc.

It's always challenging when libraries go to a non-standard API. You base your expectation around the APIs you use and then there's an outlier that causes some sort of challenge. It's very easy to grab the value from the event and it aligns with the standard across pretty much all libraries.

If you don't make that change, no big deal. I'll probably just fork so I don't have to do workarounds with react-hook-form

**Comment by benkeen** [comment]
Yeah maybe you're right. At a previous job we chose the `(value, event) => ...` param callback choice for all callbacks across our shared component library and I think it was a good one: first it was convenient, but a secondly it was done consistently for every component which made it easy to learn the pattern. But for a standalone lib like this it'd be unexpected. Cool, ok - I'll include change & add it to the breaking changes doc. Thanks for the feedback @iamclaytonray!

**Comment by benkeen** [comment]
Going to unstick this because it got dropped as a priority. I did update country-region-data@3.0.0 for es6 so this package will need an update.

**Comment by benkeen** [comment]
Closing. I didn't have time for this, which is a shame. But I do want to quickly get it updated so I've updated rollup, node, yarn & I'll do TS next.
