### ISSUE TITLE
React version is outdated

### ISSUE THREAD

**Issue by RehkMansa** [country-regions/react-country-region-selector#134]
Tried connecting it with react version 18.2.0 and I'm, having this error
![image](https://user-images.githubusercontent.com/86684329/182017440-47406759-e21a-4910-9e61-f04b009c97ec.png)

**Comment by benkeen** [comment]
Thanks. I'll check it out & try to release a new version tomorrow night. Should be perfectly compatible with React 18.

**Comment by Visualieyes** [comment]
Had this same issue, thank you! Looking forward to the updated version!

**Comment by benkeen** [comment]
I just release `3.6.0`, mind giving that a go? I did some tests and everything seemed ok. But let me know if there are any problems!

**Comment by webcodejunkie** [comment]
Is this issue closed? 
This happens to come up in my project every time I try to add a new package.
