### ISSUE TITLE
Invalid react-dom version configuration

### ISSUE THREAD

**Issue by artemkanaki** [country-regions/react-country-region-selector#135]
Hi react-country-region-selector team!

we having trouble running the `npm i` command after a recent update of the library. I noticed in your package.json that the react-dom version is `>=^15` and it causes the install command fails. I think it should be configured like `>=15`. I've attached the npm log bellow

[2022-08-03T08_29_11_564Z-debug-0.log](https://github.com/country-regions/react-country-region-selector/files/9249728/2022-08-03T08_29_11_564Z-debug-0.log)

**Comment by benkeen** [comment]
Drat, apologies. I'll release a new version tonight to patch it. Sorry for the wait.

**Comment by benkeen** [comment]
I just published `3.6.1`. Let me know if you still have problems. :)
