### ISSUE TITLE
South Korea naming convention

### ISSUE THREAD

**Issue by MattiasHenders** [country-regions/react-country-region-selector#136]
Hello!
I know officially South Korea is "Republic of Korea".
However most platforms use South Korea (Shopify, Google, etc)

Would there be anyway to change the Name of the country without changing the source data?
I like having the source data as a single source of truth

**Comment by benkeen** [comment]
Thanks! Please report all issues about the country-region data on the source `country-region-data` repo here:
https://github.com/country-regions/country-region-data
