### ISSUE TITLE
Bump version of country-region-data

### ISSUE THREAD

**Issue by ctaylor4874** [country-regions/react-country-region-selector#138]
We have a request to add Iifov to the Romanian regions and I see this update was already made in `country-region-data` repository [here](https://github.com/country-regions/country-region-data/blob/cea7e53dadba668193c3331f2bf246d50b604830/data.json#L12597-L12600). Can we bump the version and publish a new package?

**Comment by benkeen** [comment]
Ack, sorry @ctaylor4874, I missed this. Let me take a look, that's odd...

**Comment by benkeen** [comment]
Looks okay to me - I did a fresh checkout of 3.6.1 and integrated it into a separate app. I see the new Romanian region listed, however it's appearing after Brasov, rather than alphabetically. Other than that looks good.

**Comment by benkeen** [comment]
Closing this, but I'll be updating the data lib with the next release.
