### ISSUE TITLE
Region value won't reset if country gets set to `Select Country`

### ISSUE THREAD

**Issue by UndercoverNL** [country-regions/react-country-region-selector#139]
When having a country and region selected, and setting the country back to the `Select Country` value, it will reset the visual of the regions dropdown but not update the value following the `onChange` method.

using `showDefaultOption={false}` will fix this of course, but this stays a bug when not having this option set to `false`

**Comment by benkeen** [comment]
Hi @UndercoverNL! Actually state is controlled on your end, not the package itself. So on the `onChange` handler for the country you should check for a null/empty value and set the region state to blank in that condition too. 

But this is a good point. I'll update the docs to make this explicitly shown.

**Comment by benkeen** [comment]
I've updated the Basic Usage demo locally with this extra code and it'll be updated live shortly. 
https://country-regions.github.io/react-country-region-selector/demos/BasicUsage
