### ISSUE TITLE
How can i search country or state in respective dropdown 

### ISSUE THREAD

**Issue by omkarjadhav4349** [country-regions/react-country-region-selector#154]

**Comment by benkeen** [comment]
By default this script only generates plain vanilla HTML, so it only supports whatever they do natively. I believe you can type a single character for the dropdown to scroll to the first option that starts with that character. But that's pretty much it. 

However, I also just released `4.0.0` which allows for integrations for external scripts. This one using `react-select` has a searchable option:
https://country-regions.github.io/react-country-region-selector/demos/integrations/ReactSelect
