### ISSUE TITLE
Show default option in the region dropdown is configured as boolean.

### ISSUE THREAD

**Issue by Naman0701** [country-regions/react-country-region-selector#157]
![image](https://user-images.githubusercontent.com/55578641/231950653-3c0012d1-186c-4a24-8072-9286117c6a1b.png)
The type of showDefaultOption on the region drop down is string|undefined, but it should be boolean. On giving a string in the field we get this error: 
![image](https://user-images.githubusercontent.com/55578641/231950908-cb5db3cb-b9e9-4876-81c9-f6fa428edd9f.png)

**Comment by benkeen** [comment]
Resolved. `4.0.0` was released today.
