### ISSUE TITLE
Incorrect Romanian Regions

### ISSUE THREAD

**Issue by mmaddex** [country-regions/react-country-region-selector#159]
There are two issues with the current dropdown for [Counties of Romania](https://en.wikipedia.org/wiki/Counties_of_Romania)

1. Missing Bucharest (which appears to be a county and a city)
2. "lifov" should be "ilfov"

<img width="199" alt="image" src="https://github.com/country-regions/react-country-region-selector/assets/4720963/938d6d50-0fb0-4ec4-9ce3-b42fb4f4fa2b">

**Comment by srghma** [comment]
![2024-03-04-11am-20-49-screenshot](https://github.com/country-regions/react-country-region-selector/assets/7573215/a7a3aa58-a321-4773-8d1e-394ad7c54f07)

fixed

**Comment by benkeen** [comment]
For anything wrong with the data set, post on:
https://github.com/country-regions/country-region-data

That's the data source for this script.
