### ISSUE TITLE
PriorityOptions no longer works

### ISSUE THREAD

**Issue by zachary-davies** [country-regions/react-country-region-selector#176]
It doesn't seem to work on the demo site either

![Capture](https://github.com/user-attachments/assets/44bbe3cf-d227-4731-9cea-753958c2eb4f)

**Comment by benkeen** [comment]
Ooh thanks. You're quite right. I'll get a patch out soon.

**Comment by benkeen** [comment]
Thanks @zachary-davies! I just released `4.0.2` to fix it. Let me know if you spot anything else.
http://country-regions.github.io/react-country-region-selector/demos/features/PriorityOptions
