### ISSUE TITLE
Functionality to add more options to the dropdown.

### ISSUE THREAD

**Issue by shishiranshuman** [country-regions/react-country-region-selector#31]
Hello, I need to know if one of the following is possible or not:
* Add our own custom options to the dropdown list. 
* Get the region list based on the country selected. If this is possible I can push the custom options to the region list and then render it inside the `select` tag.

For example: I need to add `National` in the region dropdown:
![custom region-value](https://user-images.githubusercontent.com/20037600/35221227-6bc1d6b4-ff9f-11e7-8f22-400aca3c8db4.png)

I could not find anything related to my above problem in the docs.

Thanks

**Comment by Kostjayanch** [comment]
Hello, when would be new version release? I really wanted this feature.
Thanks

**Comment by shishiranshuman** [comment]
Hi, @Kostjayanch I have created a PR for the above feature. There are few conflicts I'll resolve them soon. 

But if you really need it urgently, you could try installing the module using the branch. Even I was doing the same. 😅

**Comment by benkeen** [comment]
Hi @shishiranshuman, 

Thanks again for your patience. 1.4.1 is out the door, so feel free to put in a PR whenever you're able.

If you have any trouble with the new rollup configuration, let me know.

Ben

**Comment by shishiranshuman** [comment]
Cool. Thanks, @benkeen 
You may expect the PW within two days.

**Comment by shishiranshuman** [comment]
@benkeen Created a PR. Please have a look.

**Comment by benkeen** [comment]
Great stuff, thanks! I'll take a look tonight after work.

**Comment by benkeen** [comment]
Thanks for adding this feature, @shishiranshuman - it'll be included in the next release. Closing.
