### ISSUE TITLE
how do i get the value of country id from the country dropdown??

### ISSUE THREAD

**Issue by hamzaahmadse** [country-regions/react-country-region-selector#37]
i want to get the country and region ids from the dropdown list
??

**Comment by benkeen** [comment]
Hi @HamzaAhmad932, there aren't really "IDs" associated with the regions or countries - only whatever value attributes you choose for them (either the full country/region name by default, or the shortcodes if you enter `valueType="short"` on the CountryDropdown/RegionDropdown components).

**Comment by pg185136** [comment]
@benkeen , Is there a way to get the 'shortCodes' when the valueType="full"? 
I need to get the short code "US" when I selected "United States of America".

**Comment by benWozak** [comment]
I was hoping for this feature as well, but it doesn't look like it's currently supported. I think the workaround for now would be to do a lookup on CountryRegionData after selecting country and region and pull the codes from there.

**Comment by aswathykrishna1804** [comment]
> @benkeen , Is there a way to get the 'shortCodes' when the valueType="full"?
> I need to get the short code "US" when I selected "United States of America".

you can try 

`
import { CountryDropdown, RegionDropdown, CountryRegionData } from 'react-country-region-selector';
`

in render

`<CountryDropdown
            value={this.state.country}
            onChange={(val) => this.selectCountry(val)}
          />`


and in onchange function

`
selectCountry(val) {
    const country = CountryRegionData.find((countryArray) => countryArray[0] === val)[1];
    this.setState({ country: val, short_country: country});
  }
`
