### ISSUE TITLE
Why is the packaged version's source data file in ./lib empty? 

### ISSUE THREAD

**Issue by TheAncientGoat** [country-regions/react-country-region-selector#4]
In order to use the widgets, I must first build it in my node modules folder with gulp? Isn't this a bit counter intuitive (and undocumented?) Why is the default export ./lib/rcrs.js and not ./dist/rcrs.js?

**Comment by benkeen** [comment]
Hey sorry for not responding. This has been rewritten in newer versions to use rollup and a more standard dist packages.
