### ISSUE TITLE
border radius

### ISSUE THREAD

**Issue by CarlosUvaSilva** [country-regions/react-country-region-selector#41]
I'm trying to remove the border-radius of the dropdown but I can't seem to do it.
I'm trying border-radius: unset and it overrides the default 5px but the component doesn't change

**Comment by benkeen** [comment]
Hi Carlos, the dropdowns/select boxes are just plain HTML, so styling may be limited to whatever your browser permits. But you should be able to style them to change the border radius. 

https://stackoverflow.com/questions/1895476/how-to-style-a-select-dropdown-with-only-css
