### ISSUE TITLE
Sync data with country-region-data - Metro Manila

### ISSUE THREAD

**Issue by leschaller1** [country-regions/react-country-region-selector#43]
Could you publish a version of react-country-region-selector with the latest data from [country-region-data](https://github.com/benkeen/country-region-data)? My PR to add Metro Manila for the Philippines was merged recently https://github.com/benkeen/country-region-data/pull/34

**Comment by benkeen** [comment]
Thanks @leschaller1  - will do. I'll update it in 1.4.0.
