### ISSUE TITLE
Missing Gulpfile

### ISSUE THREAD

**Issue by lightninglu10** [country-regions/react-country-region-selector#48]
Hey guys, how do you build? There's no build command inside the package.json and no gulpfile as specified by the README.

**Comment by benkeen** [comment]
Ah, sorry - master is in development. Check out the latest release and build the code off that. 
https://github.com/benkeen/react-country-region-selector/tree/1.3.0

I'll update the main readme to clarify this. Thanks!

**Comment by benkeen** [comment]
I've just released 1.4.1 that moves everything to rollup. The README includes info on how to build. 

Thanks!
