### ISSUE TITLE
Regarding validation

### ISSUE THREAD

**Issue by jurjees23** [country-regions/react-country-region-selector#53]
how to set required validation for country and region field

**Comment by benkeen** [comment]
Hi @jurjees23, there's nothing in the script for validation. But you can do validation however you want: your component will house the values in the two dropdowns so you can use that information to determine error states and display whatever errors you need in your form. 

All the best!

**Comment by jurjees23** [comment]
> Hi @jurjees23, there's nothing in the script for validation. But you can do validation however you want: your component will house the values in the two dropdowns so you can use that information to determine error states and display whatever errors you need in your form.
> 
> All the best!
Thank you for your information

**Comment by oskarer** [comment]
@jurjees23 You can set the `required` prop on `CountryDropdown` and `RegionDropdown` to enable regular HTML5 form validation.
