### ISSUE TITLE
Ability to add list of popular/common countries to top

### ISSUE THREAD

**Issue by zamirkhan** [country-regions/react-country-region-selector#55]
I believe this is a feature request for functionality not currently supported, but please correct me if I'm mistaken. 

I would like to be able to list a set of countries that would appear at the top of the list, separated by a vertical line from the overall alphabetical list. The top list would include the countries that are the most common choices of my users. 

For example:

United States
Canada

-----------

Afghanistan
Aland Islands
...

The common countries would then be repeated in the list below. I don't believe I can accomplish this with whitelist and blacklist, but let me know if that's a wrong assumption.

**Comment by benkeen** [comment]
Yeah. There's actually an old PR in for this very feature which I didn't merge in a timely fashion.
https://github.com/country-regions/react-country-region-selector/pull/27

I'll get that patched up and merged in this weekend and release a new version then.

Thanks!
