### ISSUE TITLE
How to properly select Default values

### ISSUE THREAD

**Issue by ferrucc-io** [country-regions/react-country-region-selector#62]
Hi there,

I've been using react-country-region-selector in my project, but I'm having trouble figuring out how to properly make an "update" page.

By specs we are not allowed to specify defaultValue, so I was wondering if at the moment this isn't supported. I'd also need to specify a defaultCountry in the region selector.

At the moment I'm using `defaultOptionLabel` and `blankOptionLabel` but this breaks the form as the country isn't really selected, only its name is shown. 
Same goes for the region selector, which instead is completely broken as the dropdown to change region only works after changing the country.

I'm wondering if I'm using the library in the wrong way or if this is not supported and you'd accept a PR that adds these features.

Here's my current code at the moment for reference 👇 

```jsx
<fieldset disabled={loading} aria-busy={loading}>
                    <label htmlFor="country">
                      Country
                      <CountryDropdown
                        defaultValue={data.user.country}
                        name="country"
                        id="country"
                        value={this.state.country}
                        onChange={val => this.selectCountry(val)}
                        defaultOptionLabel={data.user.country}
                      />
                    </label>
                  </fieldset>
                  <fieldset disabled={loading} aria-busy={loading}>
                    <label htmlFor="region">
                      Region
                      <RegionDropdown
                        defaultValue={data.user.region}
                        name="region"
                        id="region"
                        country={this.state.country}
                        value={this.state.region}
                        onChange={val => this.selectRegion(val)}
                        blankOptionLabel={data.user.region}
                        defaultOptionLabel={data.user.region}
                      />
                    </label>
                  </fieldset>
```

**Comment by benkeen** [comment]
Hey @ferrucc-io! Sorry for not responding sooner. 

Hmm... did you check out example #9 here? 
http://country-regions.github.io/react-country-region-selector/

That shows how to set the default country and region from your own values:

```
<CountryDropdown
    value="United States"
    onChange={selectCountry} />
 <RegionDropdown
    country={country}
    value="Washington"
    onChange={selectRegion} />
```

Does rather looks like your code is fine though... are you sure your country and region data being passed in is correct?

**Comment by florpistan** [comment]
Hi there @ferrucc-io ! Did you resolve this? I'm having the same issue

**Comment by benkeen** [comment]
This is extremely old, so I'll close. Don't think it's still an issue.
