### ISSUE TITLE
Component has a strict shouldComponentUpdate method, preventing things like className changes

### ISSUE THREAD

**Issue by mattclough1** [country-regions/react-country-region-selector#69]
If I need to change any props on the RegionDropdown component (and presumably other components in the lib), it won't work because it has a very restrictive shouldComponentUpdate method. Is there any reason to not just make this a PureComponent?

https://github.com/country-regions/react-country-region-selector/blob/f12b1d7aa8b915eec4db202ebe25081d5eba6326/src/RegionDropdown.js#L16

**Comment by benkeen** [comment]
Thanks for the heads up, @mattclough1. Yeah this needs to change - and yes, a PureComponent seems perfectly reasonable for this. 

A few other people have noted that it's failing to update once the props change; I'll include a fix for this this in the next release.

**Comment by mattclough1** [comment]
Thanks @benkeen!

**Comment by benkeen** [comment]
I just published the new version. Note: I'm having some glitches updating the github pages demo. Will figure it later out today.
