### ISSUE TITLE
Multiple selections?

### ISSUE THREAD

**Issue by ksnyder** [country-regions/react-country-region-selector#70]
Does this library support selecting multiple countries?  The Readme says that any attributes not specific to this library will be used in the <Select> tag but none of these get passed through:

multiple,
multiple = { true },
multiple = '',
multiple = 'true',

**Comment by benkeen** [comment]
Ah interesting... that's true, those ones probably won't work. The component relies on having a single country value to determine what regions to show. It currently wouldn't know how to behave if there were multiple countries selected. How would you like it to behave, btw? Perhaps group the regions in an `<optgroup>`, one for each country?
