### ISSUE TITLE
required attribute

### ISSUE THREAD

**Issue by Rc85** [country-regions/react-country-region-selector#72]
The dropdown inputs need a required attribute for form validation

**Comment by benkeen** [comment]
Hi @Rc85, this should work as-is. Any properties passed to the two components that aren't explicitly defined should be output onto the DOM element. Let me know if this isn't the case.

**Comment by Rc85** [comment]
It's not working in my case. Not sure what I'm doing wrong. I simply just added a "required" prop.

onBlur works, but onFocus doesn't. The readme has onBlur listed as one of its props, so maybe that's why. This leads me suspect that built-in component props are not passed in.

**Comment by Rc85** [comment]
Appears to be working now. Maybe I was doing something wrong.

**Comment by ig4ever** [comment]
> Appears to be working now. Maybe I was doing something wrong.

can you provide the solution? i can't directly pass required props
