### ISSUE TITLE
How can I trigger onClick using some other button or element having onClick?

### ISSUE THREAD

**Issue by rishabhzvky** [country-regions/react-country-region-selector#75]

**Comment by benkeen** [comment]
Hey @rishabhzvky, have you tried adding an onClick prop to the components? Any arbitrary props should be passed on the the DOM element, so it should work. 

But right now there's no way to trigger it to show the dropdown - for that it really needs to expose the `ref` for ref forwarding, so you can do it manually. I'd be happy to take a pull request if anyone want to add that.
