### ISSUE TITLE
componentWillReceiveProps deprication warning

### ISSUE THREAD

**Issue by gmpofficial** [country-regions/react-country-region-selector#77]
Receiving this warning in version 1.4.4 of react-country-region-selector with React version 16.10.2.

> Warning: componentWillReceiveProps has been renamed, and is not recommended for use. See https://fb.me/react-unsafe-component-lifecycles for details.
> 
> * Move data fetching code or side effects to componentDidUpdate.
> * If you're updating state whenever props change, refactor your code to use memoization techniques or move it to static getDerivedStateFromProps. Learn more at: https://fb.me/react-derived-state
> * Rename componentWillReceiveProps to UNSAFE_componentWillReceiveProps to suppress this warning in non-strict mode. In React 17.x, only the UNSAFE_ name will work. To rename all deprecated lifecycles to their new names, you can run `npx react-codemod rename-unsafe-lifecycles` in your project source folder.
> 
> Please update the following components: RegionDropdown

I have manually changed **componentWillReceiveProps** to **componentDidUpdate** in the source code but would be good to have it fixed in the next update :)

**Comment by benkeen** [comment]
Thanks @gmpofficial. I'll take a look at this.

**Comment by benkeen** [comment]
I just released 1.4.5 which includes a few updates, including this one. Let me know if you have any problems. Thx!

**Comment by solomonakp** [comment]
error still persists cause i am having it right now
