### ISSUE TITLE
Does it works with React native?

### ISSUE THREAD

**Issue by schmem55** [country-regions/react-country-region-selector#86]
hi 
i would like to use it with react native but i receive this error

Invariant Violation: Text strings must be rendered within a <Text> component.

react native 0.59.10

**Comment by benkeen** [comment]
Hi @schmem55, no I'm afraid react-native is a very different creature indeed. You'll need to use react-native components for dropdowns. This script won't work with that.

**Comment by schmem55** [comment]
@benkeen  
thanks

**Comment by ncoen97** [comment]
@schmem55 
Hi! Did you found any other options for react native?
I came across react-native-country-picker-modal but it only ollows you to select the country 😢
