### ISSUE TITLE
country-region-data for Finland is not reflecting the 1.5.1 release

### ISSUE THREAD

**Issue by dareiff** [country-regions/react-country-region-selector#87]
I’ve checked devDependencies, and it’s pointing to the 1.5.1 release, but the region information for Finland is reflecting pre-1.5.1 data.

<img width="447" alt="Screen Shot 2020-03-24 at 10 25 37 AM" src="https://user-images.githubusercontent.com/435896/77457370-d0f02d80-6db9-11ea-9f4c-0624d0a36c94.png">

**Comment by benkeen** [comment]
Ah I see. My bad, I didn't notice you made the change to the `data.js` file - the source is actually `data.json` - so it was overwritten. I'll update the contribution doc to make it clearer and release a new version shortly.

**Comment by benkeen** [comment]
I just released 2.1.0 that includes this fix. Thanks @dareiff.
