### ISSUE TITLE
v3.0.0 with hooks, updated dependencies, and forward ref

### ISSUE THREAD

**Issue by dojr** [country-regions/react-country-region-selector#92]
Hey @benkeen I've made some progress on updating the library in my fork here https://github.com/dojr/react-country-region-selector

I've converted the tests and updated each dropdown to use hooks and forward the ref.

I've also updated some of the dependencies including babel and added jest with the testing library and removed enzyme.

I experimented with the publishing library ship.js but I'm still unsure on how it can best fit the needs of an open source library. It can be installed with `npm i @dojr/react-country-region-selector` 

I tested it out in my own project and the forward ref and basic functionality all seems to work the same as before. 

In any case, I'll probably cherry-pick the commits with the necessary updates and make a PR to the library (maybe a PR to a v3.0.0 branch). Before doing so though I wanted to get your opinion on how it looks so far and any suggestions or recommendations you might have.

Thanks!

**Comment by benkeen** [comment]
Hey @dojr, nice! How about just put in a PR now against master? Yes, this'll be a 3.0.0 release but I can do all that after merging your code in. A PR will help me see the changes you made so I can give better feedback.

**Comment by benkeen** [comment]
This change will be included in 4.0.0.

**Comment by benkeen** [comment]
Closing. `4.0.0` released.
