### ISSUE TITLE
Read only option

### ISSUE THREAD

**Issue by abdellatifLabr** [country-regions/react-country-region-selector#96]
This is a feature request
We would like to have a readOnly option for both country select & region select components.

**Comment by benkeen** [comment]
Hi @abdellatifLabr! If you pass `readOnly` to either element, that should end up on the generated `<select>` elements. But may I ask, what would this be needed for? Just curious. You can always add a `disabled` prop to prevent the user from changing the values.

**Comment by abdellatifLabr** [comment]
@benkeen I'm using a ui library that has style difference between disabled & read only

**Comment by benkeen** [comment]
Ah, thanks! Yes, let me know if passing that prop doesn't work - but it should be fine.
