### ISSUE TITLE
Missing blacklist prop from RegionDropdown component

### ISSUE THREAD

**Issue by dan003400** [country-regions/react-country-region-selector#98]
You should be able to blacklist an array of regions no matter which country is selected.

You would also want to be able to dynamically set this array based on which country is selected to remove certain regions.

**Comment by dan003400** [comment]
Looks like there is already a PR for this, can we get this merged in? - #38

**Comment by benkeen** [comment]
Sure, let me take a look at this tonight.

**Comment by dan003400** [comment]
Awesome, let me know if you need any help.

**Comment by benkeen** [comment]
I've merged it in, plus a couple of other additions, but I'll need a couple of days to tidy everything up and get it into a release. If you don't see a new version by Sunday or Monday, feel free to bug me :)

**Comment by dan003400** [comment]
Sounds good, much appreciated 🎉

**Comment by benkeen** [comment]
Sorry, gotta bump this to tomorrow night.

**Comment by dan003400** [comment]
No problem at all.

Are there any thoughts to make it easier to supply your own datasets?

Thanks!

**Comment by benkeen** [comment]
Hey Dan, I just released 3.0.0 which includes the new blacklist & whitelist feature. Demo here (rows 10 & 11): http://country-regions.github.io/react-country-region-selector/

The integration with the country-region-data dataset isn't that great... I think were I to approach this today, I'd maybe do something like this. Export a `<RCRSProvider>` from this package that you could wrap both the `<CountryDropdown />` and `<RegionDropdown />` and have it define a prop where you'd explicitly pass the country region data, like:

```
import data from 'country-region-data';
import { CountryDropdown, RegionDropdown, CRProvider } from 'react-country-region-selector';

const Component = () => (
    <CRProvider data={data}>
        <CountryDropdown ... />
        <RegionDropdown ... />
    </CRProvider>
);
```

That'd then make passing different data a breeze. Just a question of providing it in the right format.

**Comment by dan003400** [comment]
Ah this is perfect. I will give it a try.

Thanks a ton. Let me know how I can ever help on anything else going forward.

**Comment by dan003400** [comment]
@benkeen  - Doesnt look like a <CRProvider> is exported from your package. Have you actually tried the code above?

**Comment by benkeen** [comment]
Hmm, I've just used it via in the examples - but that should consume the build artifacts so should be good. I'll take a look tonight, sorry about that.

**Comment by dan003400** [comment]
Recently published a cleaned up typescript version of this repo here:

https://www.npmjs.com/package/@bettercart/react-country-region-selector

This also includes the context provider for custom data, we also pushed a new version of the data that is much cleaner, more accurate and it also includes some meta like zip_required.

https://www.npmjs.com/package/@bettercart/country-region-data

Let me know your thoughts!

**Comment by benkeen** [comment]
Ah sorry, perhaps we're talking cross-purposes. That code I posted above was just a suggestion of how I'd refactor this - it's not implemented I'm afraid. 

And nice!!! That's fantastic - any chance you'd put a PR in? I've love to convert it to TS and providing the context provider would be a terrific addition! Maybe put in a PR and I'll look it over there.
